name: CICD

jobs: 
        build-and-push:
                  runs-on: ubuntu-latest #GitHub Runner
                  steps:  
                          -users: actions/checkout@v4 # clone the code

                          -users: docker/setup-buildx-action@v4
